---
- name: NY4 Expansion QA
  hosts: all
  gather_facts: no
  connection: local
  vars:
    commands:
        - conf t
        - ntp source-interface loopback0
        - end
        - wr
  tasks:
  - nxos_command:
      provider:
        # Use enable mode?
        authorize: yes
      commands: "{{ commands }}"
    register: results

  - debug:
     msg: "{{ results }}"
