---
- name: NY4 Expansion QA
  hosts: all
  gather_facts: no
  connection: local
  vars:
    commands:
        - conf t
        - ip pim rp-address 10.29.9.184 group-list 239.255.82.0/24
        - ip pim rp-address 10.29.9.185 group-list 239.255.83.0/24
        - ip pim rp-address 10.29.9.188 group-list 239.255.88.0/24
        - end
        - wr
  tasks:
  - nxos_command:
      provider:
        # Use enable mode?
        authorize: yes
      commands: "{{ commands }}"
    register: results

  - debug:
     msg: "{{ results }}"
